name: Merge release branch into master branch

on:
  issue_comment:
    types: [created]

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/test-release-branch-workflow')
    steps:
      - name: Debug script
        run: |
            IS_PR="${{ github.event.issue.pull_request }}"
            GH_REF="${{ github.ref }}"
            COMMENT_BODY="${{ github.event.comment.body }}"
            echo Is PR $IS_PR ref $GH_REF comment body $COMMENT_BODY $GITHUB_EVENT_EVENT_COMMENT_BODY

