name: Merge release branch into master branch

on:
  issue_comment:
    types: [created]

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/test-release-branch-workflow')
    steps:
      - name: Debug script
        env:
          IS_PR: ${{ github.event.issue.pull_request }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo Is PR $IS_PR ref $GITHUB_REF comment body $COMMENT_BODY

