name: Merge release branch into master branch

on:
  issue_comment:
    types: [created]

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test-release-branch-workflow')
    steps:
      - id: get_branch_name
        run: echo "branch=$(gh pr view $PR_NUMBER --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release branch
        id: verify_release_branch
        env:
          PR_BRANCH: ${{ steps.get_branch_name.outputs.branch }}
        run: |
          echo $
          if [[ "$PR_BRANCH" != "release/"* ]]; then
            echo "This workflow only runs for release branches. Stopping the workflow..."
            exit 1
          fi

      - name: Debug script
        run: |
          IS_PR="${{ github.event.issue.pull_request }}"
          GH_REF="${{ github.ref }}"
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo Is PR $IS_PR ref $GH_REF comment body $COMMENT_BODY

