name: Merge release branch into master branch

on:
  issue_comment:
    types: [created]

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/release-branch-workflow')
    steps:
      # see https://github.com/actions/checkout/issues/331#issuecomment-1035525003
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=$(gh pr view $PR_NUMBER --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release branch
        id: verify_release_branch
        env:
          PR_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          echo Current branch: $PR_BRANCH
          if [[ "$PR_BRANCH" != "release/"* ]]; then
            echo "This workflow only runs for release branches. Stopping the workflow..."
            exit 1
          fi

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      # Do a ff-only merge from the release branch into master
      # Push changes from the release branch into master
      # This also automatically closes the release branch PR
      - name: Merge to main ff_only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          git fetch origin main
          git fetch origin $PR_BRANCH
          git checkout $PR_branch
          git pull
          git checkout main
          git pull --rebase
          git merge $PR_BRANCH --ff-only --allow-unrelated-histories
          git push origin main


